on:
    push:
        paths:
            - "package.json"

name: Deploy Extension
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci

            - name: Check if version changed
              id: check_version
              run: |
                  if git diff HEAD^ HEAD -- package.json | grep '"version":'; then
                      echo "VERSION_BUMPED=true" >> $GITHUB_ENV
                  else
                      echo "VERSION_BUMPED=false" >> $GITHUB_ENV
                  fi

            - name: Publish to Visual Studio Marketplace
              if: env.VERSION_BUMPED == 'true'
              uses: HaaLeo/publish-vscode-extension@v2
              with:
                  pat: ${{ secrets.VSCE_TOKEN }}
                  registryUrl: https://marketplace.visualstudio.com
